services:
  server:
    container_name: server
    build:
      context: .
    environment:
      - MONGODB_URL=mongodb://db:27017
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - s2s-network
  
  db:
    container_name: db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    expose:
      - 27017
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - s2s-network
    
volumes:
  db-data:

networks:
  s2s-network:
    name: s2s-network
    driver: bridge
